from application.response_handlers.albums.single_album import GetSingleAlbumResponseHandler
from application.response_handlers.albums.several_albums import GetSeveralAlbumsResponseHandler
from application.response_handlers.artists.single_artist import GetSingleArtistResponseHandler
from application.response_handlers.artists.several_artists import GetSeveralArtistsResponseHandler
from application.response_handlers.me.my_liked_songs import LikedSongsPlaylistResponseHandler
from application.response_handlers.tracks.single_track import GetSingleTrackResponseHandler
from application.response_handlers.tracks.several_tracks import GetSeveralTracksResponseHandler
