#!/usr/bin/env bash
#
# Per-worktree Docker Compose isolation: writes IMAGE_TAG + COMPOSE_PROJECT_NAME
# into the worktree's gitignored .env, and a port-stripping compose.override.yaml,
# so parallel worktrees don't collide on one Docker daemon. Deliberate NO-OP
# outside .claude/worktrees/* — the primary checkout keeps shared defaults.
# Wired as a SessionStart hook in .claude/settings.json; safe to run by hand.
# Why + details: docs/delivery.md#parallel-checkouts-the-worktree-trick
set -euo pipefail

root="${CLAUDE_PROJECT_DIR:-}"
if [ -z "$root" ]; then
    root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
fi
[ -n "$root" ] || exit 0

# Only isolate ephemeral Claude worktrees; never touch the primary checkout.
case "$root" in
    */.claude/worktrees/*) ;;
    *) exit 0 ;;
esac

branch="$(git -C "$root" rev-parse --abbrev-ref HEAD 2>/dev/null || echo detached)"
# Sanitize to a valid Docker tag / compose project name: lowercase, and every
# character outside [a-z0-9_-] (notably the '/' in claude/xxx) becomes '-';
# then trim to a leading alphanumeric and no trailing dash.
slug="$(printf '%s' "$branch" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -e 's/[^a-z0-9_-]/-/g' -e 's/^[^a-z0-9]*//' -e 's/-*$//')"
[ -n "$slug" ] || slug="worktree"

env_file="$root/.env"
tag="$slug"
project="spotify-power-browser-$slug"

# Idempotent upsert of our two keys; preserve any other .env lines the user set
# (RESET_CRAWL, USE_BATCH_ENDPOINTS, ...). The grep also strips the legacy
# *_PORT_MAP keys an older version of this hook wrote — host ports are now
# dropped via compose.override.yaml (below), not randomized here.
touch "$env_file"
tmp="$(mktemp "${TMPDIR:-/tmp}/spb-env.XXXXXX")"
grep -vE '^(IMAGE_TAG|COMPOSE_PROJECT_NAME|RABBITMQ_AMQP_PORT_MAP|RABBITMQ_MGMT_PORT_MAP|AUTH_PORT_MAP)=' "$env_file" > "$tmp" || true
{
    echo "IMAGE_TAG=$tag"
    echo "COMPOSE_PROJECT_NAME=$project"
} >> "$tmp"
mv "$tmp" "$env_file"

# Worktree stacks publish NO host ports: the per-project network already
# connects the services, and publishing would fight the primary checkout (and
# sibling worktrees) for the host's 5672/15672/8000. compose auto-merges this
# override; `ports: !reset []` clears the compose.yaml mappings (needs Compose
# v2.24+ for the !reset tag).
cat > "$root/compose.override.yaml" <<'OVERRIDE'
# GENERATED by scripts/worktree_compose_env.sh (SessionStart hook) — do not edit.
# Isolated worktree stacks publish no host ports; delete this file (or run from
# the primary checkout, where the hook never writes it) to restore the
# compose.yaml host-port mappings.
services:
  rabbitmq:
    ports: !reset []
  spotify_authentication:
    ports: !reset []
OVERRIDE

echo "[compose-isolation] worktree '$branch' -> image spotify-power-browser:$tag, compose project $project (no host ports published)"
